name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test and Build
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:7
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: root_password
          MONGO_INITDB_DATABASE: my_api_test
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --username root --password root_password --authenticationDatabase admin --eval 'db.adminCommand(\"ping\")'"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 10

    env:
      MONGO_TEST_URI: mongodb://root:root_password@127.0.0.1:27017/my_api_test?authSource=admin
      MONGO_TEST_DATABASE: my_api_test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26.5"
          cache: true

      - name: Download dependencies
        run: go mod download

      - name: Check formatting
        run: |
          unformatted="$(gofmt -l .)"

          if [ -n "$unformatted" ]; then
            echo "The following files are not formatted:"
            echo "$unformatted"
            exit 1
          fi

      - name: Run go vet
        run: go vet ./...

      - name: Run tests
        run: go test ./...

      - name: Run integration tests
        run: go test -tags=integration -count=1 ./...

      - name: Build
        run: go build -o bin/my-api ./cmd/api

      - name: Build Docker image
        run: |
          docker build \
            -f deployments/docker/Dockerfile \
            -t my-api:${{ github.sha }} \
            .